### ISSUE TITLE
Concurrent mod error

### ISSUE THREAD

**Issue by CBrophy** [zulily/omicron#38]
[Mon Aug 31 18:36:00 UTC 2015] SEVERE: Exception while retiring old tasks or sending notifications
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.zulily.omicron.sla.Policy.evaluate(Policy.java:120)
	at com.zulily.omicron.alert.AlertManager.sendAlerts(AlertManager.java:100)
	at com.zulily.omicron.scheduling.JobManager.run(JobManager.java:99)
	at com.zulily.omicron.Main.main(Main.java:113)

**Comment by CBrophy** [comment]
Iterating from set view while removing

**Comment by CBrophy** [comment]
Fixed 1.2+
